### ISSUE TITLE
Can't put it to desktop will these cause issues?

### ISSUE THREAD

**Issue by SayPex** [TriizzyxOT/BO6-ESP-Aimbot#15]
[
![Screenshot 2024-12-02 150951](https://github.com/user-attachments/assets/ce5a5184-712c-48d3-94fd-1a51e4395ef4)
![Screenshot 2024-12-02 151052](https://github.com/user-attachments/assets/ab6c318c-4b0c-45fa-aab7-912636fb4ed6)
](url)

**Comment by TriizzyxOT** [comment]
shouldnt cause any issues but it seems that your file permissions may be conflicting. try again on an administrator account!
