### ISSUE TITLE
I'm loading the chair but the menu to inject isn't popping up

### ISSUE THREAD

**Issue by SayPex** [TriizzyxOT/BO6-ESP-Aimbot#16]

**Comment by SayPex** [comment]
![Screenshot 2024-12-02 154613](https://github.com/user-attachments/assets/0d77c119-0069-438e-9411-ddc34fd2d2f4)

**Comment by SayPex** [comment]
![Screenshot 2024-12-02 155035](https://github.com/user-attachments/assets/82f45caf-b549-426a-b52e-b79e094313a4)

**Comment by SayPex** [comment]
![Screenshot 2024-12-02 155526](https://github.com/user-attachments/assets/8d992be0-6416-4eff-a4d1-beac258116a4)

**Comment by TriizzyxOT** [comment]
refer to your previous issue please!
