### ISSUE TITLE
Unable to run chair.exe

### ISSUE THREAD

**Issue by NickP1018** [TriizzyxOT/BO6-ESP-Aimbot#17]
Good evening,

When I attempt to run Chair.exe, it silently runs. I get a popup from Windows Defender Firewall, but I am able to bypass it. My Real-Time & Cloud Delivered protection services are off, and I have no additional Antivirus tools which are active. My windows version is 23H2. 

Chair.exe shows in my task manager, however it is not seeming to do much. Any feedback?

Thank you

**Comment by TriizzyxOT** [comment]
check most recent version, just put out a new update.
