### ISSUE TITLE
Recurring issue during new release

### ISSUE THREAD

**Issue by NickP1018** [TriizzyxOT/BO6-ESP-Aimbot#18]
Good evening, 

I just downloaded the new patched Chair.exe and am having the same issues as I did in the last Issue Forum. Any idea what may be the cause?

![image](https://github.com/user-attachments/assets/31ddb67f-a523-493e-a9b2-404f0b382f4e)
![image](https://github.com/user-attachments/assets/39bc55fb-32db-49fb-858d-71559d554f10)
![image](https://github.com/user-attachments/assets/71fb15d5-c0c1-4338-9620-4b5b57a03564)

**Comment by NickP1018** [comment]
Forgot to mention, when I run the Chair.exe file, it slowly ramps to 20% CPU usage then ramps back down to 0% within the span of 10 seconds or so. Hope this helps!

**Comment by TriizzyxOT** [comment]
Windows 11 has been quite finicky, we will be working on it over the weekend and will hopefully have some better stability on windows 11. most of our user base is windows 10, so those are the fixes weve been focusing on. Apologies for the delay!

**Comment by NickP1018** [comment]
No worries, thanks for the update!
