### ISSUE TITLE
Recurring Issues

### ISSUE THREAD

**Issue by NickP1018** [TriizzyxOT/BO6-ESP-Aimbot#19]
Good Evening again.

I decided to take it upon myself to test whether it was my Windows version which was causing the issues and it does not seem to be that. I downgraded my PC to Windows 10 Home, version 22H2. 

![image](https://github.com/user-attachments/assets/311452e3-994f-4c63-8281-3e5d4831f8fc)

I disabled real-time protection and cloud-delivered protection as well.

![image](https://github.com/user-attachments/assets/8c184ba1-7dc0-4a8a-b935-bf7ab8bd5de8)

Yet, when I run the new Chair.exe file, I get the same issue as before. It loads with an admin screen, and boots to nothing. It appears in Task Manager for about 10 minutes while using about 25MB of ram. Any ideas?

**Comment by NickP1018** [comment]
Also, when I attempt to run Call of Duty when Chair.exe is running the game its self works with no issue. No menus pop up and it does not auto-close like before.

**Comment by TriizzyxOT** [comment]
hmm. what system specs??

**Comment by TriizzyxOT** [comment]
also you said it was autoclosing cod on win 11?

**Comment by NickP1018** [comment]
I apologize for the wait, I was sleeping.

System Specs:
CPU: Intel Core i7 - 10700F @ 2.9GHz
GPU: NVIDIA GeForce RTX 3090 Ti
RAM: 64GBs of DDR4
WiFi: 900Mbps Download & 900Mbps Upload

Also, it was not that Call of Duty was autoclosing, it was not actually running. When I attempted to launch via Steam, it would say "X Running" and after about 20 seconds it would go back to "> Play". The game its self never actually launched

**Comment by NickP1018** [comment]
I've also attempted to run it out of a few different locations:
Downloads Folder
Desktop
D: Drive

None of which worked. Same issue.

**Comment by TriizzyxOT** [comment]
Please try the updated version, i have addressed some issues in the startup code causing the process to hang. Thanks for the feedback!!

**Comment by TriizzyxOT** [comment]
Please try the updated version, we have addressed some issues in the startup code causing the process to hang. Thanks for the feedback!!
