### ISSUE TITLE
My games doesn't launch

### ISSUE THREAD

**Issue by SeisseONGithub** [TriizzyxOT/BO6-ESP-Aimbot#22]
After installing the.exe and disabling the classic and cloud firewalls. I start cod and nothing starts, the taskbar is empty...I restarted the and nothing...(the script is loaded by steam the first time I press the"play" button on the app)

**Comment by TriizzyxOT** [comment]
A new version has been released, please try the updated version and run Chair.exe separately from steam, meaning launch chair.exe first, then launch Call Of Duty.

**Comment by SeisseONGithub** [comment]
The game now launches but without the menu...thanks
