### ISSUE TITLE
Wont load, ran through VT

### ISSUE THREAD

**Issue by jTr-0** [TriizzyxOT/BO6-ESP-Aimbot#25]
https://www.virustotal.com/gui/file/5a4fab28577f9d9eb80d564fb83e749ae65b7968df85a220aed278cbc0e54ce2

**Comment by TriizzyxOT** [comment]
yeah those detections are because A: its a memory based cheat and B: I obfuscate my files to keep them from being reverse engineered in turn detected by anticheat
