### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by Julien-a4** [TriizzyxOT/BO6-ESP-Aimbot#26]
Hi, I've been following your project for a few weeks, it's a great initiative. However, it still doesn't work for me when I run chair.exe I don't have anything opening. Do you have a solution?

-Windows 10 22h2 
-xbox gamepass platform 
-all windows defender disable 
-firewall disabled 
-internet protection file disabled

**Comment by TriizzyxOT** [comment]
have been reworking the entirety of the code and swapping frameworks for better stability and handling of calls, should be done by tomorrow. my apologies, this last update was more focused on AC detections.
