### ISSUE TITLE
chair file keeps getting deleted after trying to open

### ISSUE THREAD

**Issue by bluntgod225** [TriizzyxOT/BO6-ESP-Aimbot#41]
after downloading the file with all virus protections it says off my chair file keeps getting deleted from computer

**Comment by TriizzyxOT** [comment]
Please ensure you have any third party antivirus protections disabled before downloading the file as they may interfere with operation of the cheat.

**Comment by bluntgod225** [comment]
i dont have any 3rd party antivirus just the windows defender through
settings
