### ISSUE TITLE
trojan

### ISSUE THREAD

**Issue by Julien-a4** [TriizzyxOT/BO6-ESP-Aimbot#5]
trojan detected even with all antivirus disabled

**Comment by TriizzyxOT** [comment]
Windows Defender and other antivirus programs give false-positives for any program that uses memory injection, cheat loaders rely on memory injection to function. Please ensure that you have disabled Windows Defender Real-Time Protection and Cloud-Based Protection DISABLED as explained in the README. If you get a Microsoft Defender SmartScreen window blocking the program from running please select more info and Run Anyways, as it is detecting the memory injection function of the loader and marking it as a virus/trojan.
