### ISSUE TITLE
Ordinal 345 not found

### ISSUE THREAD

**Issue by Julien-a4** [TriizzyxOT/BO6-ESP-Aimbot#6]
Hi, after downloading the chair.exe link nothing runs or opens, and when I try to run the game it doesn't work, I get an error message "ordinal 345 not found" and after " the game is blocked" do you have a solution pls? Do you have discord it will be simpler?

**Comment by TriizzyxOT** [comment]
This appears to be an issue with your game files, possible corruption/missing files. Can you attach a screenshot? Still in the works of getting a discord up and made, should be up in the next few days. Thanks!
