### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Julien-a4** [TriizzyxOT/BO6-ESP-Aimbot#7]
I come back to the news, I just reformatted my computer and downloaded the games again but it's still the same thing, my Windows version is 22h2, I play on Xbox Game Pass platform, my file is located 

OS(C:)/XboxGames/Call Of Duty/    

Should I have it move?

I proceeded as follows,

1: Disable Real-time protection and Cloud-delivered protection

2: Download chair.exe, run chair.exe (there is nothing happening, no file open)

3: I launch the game but it sends me error messages (explained ticket 6), and the game closes

**Comment by TriizzyxOT** [comment]
i have not personally tested on gamepass version of bo6. i have tested steam, steam is confirmed working. Are you able to run the game without the loader launched?

**Comment by Julien-a4** [comment]
Yes I can

**Comment by Julien-a4** [comment]
You don’t have a solution for me? If you want test on Gamepass xbox, its just 1€ for 1month

**Comment by Julien-a4** [comment]
what platform are you on? steam or gamepass, because he said that on steam there was no functioning problem, for me gamepass it does not work

**Comment by browniemade** [comment]
happening to me too ):

**Comment by Julien-a4** [comment]
Not yet, maybe he will release a gamepass version in the next days otherwise for now no solution

**Comment by TriizzyxOT** [comment]
Gamepass fix will be released this weekend, still working out some bugs. Apologies for the delay.

**Comment by UTUSPAC** [comment]
I am on battle net

Il lun 18 nov 2024, 22:39 Julien-a4 ***@***.***> ha scritto:

**Comment by UTUSPAC** [comment]
ok thanks... but when will the updates be released? but which ones do you
mean, the ones for call of duty or the cheat?

Il mar 19 nov 2024, 20:25 TriizzyxOT ***@***.***> ha scritto:
